public class MyException {
    public static void main(String[] args) {
        throw new RuntimeException("문제가 발생했습니다");
    }
}